### Recuperar todas las peliculas
GET http://localhost:1234/movies


### Rrecuperar una pelicula por id
GET http://localhost:1234/movies/7e3fd5ab-60ff-4ae2-92b6-9597f0308d1

### recuperar todas las películas de un género

GET http://localhost:1234/movies?genre=Action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "El señor de los anillos: La comunidad del Anillo",
    "year": 2003,
    "director": "J.R.R. Tolkien",
    "duration": 179,
    "poster": "https://pics.filmaffinity.com/the_lord_of_the_rings_the_fellowship_of_the_ring-952398002-large.jpg",
    "genre": [
        "Fantasy",
        "Adventure",
        "Action"
    ]
}

### Actualizar una pelicula una parte por id
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "id": 123,
    "title": "Hola",
    "year": 2000
}
